runtime: python38

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: map.html
  upload: map\.html

- url: /map\.html
  static_files: map.html
  upload: map\.html

- url: /api_key\.js
  static_files: api_key.js
  upload: api_key\.js

- url: /.*
  script: auto

